### PR TITLE
Extended Soft Body functions

### PR DESCRIPTION
**Pull request by donalffons**

### CODE REVIEW

**Comment by donalffons** [comment]
Hi Lubos, for some reason github is having issues with showing the differences in this pull request... Sorry for that. 
Please, let me know if this can be accepted or not. Also let me know, if anything should be changed before merging.

**Comment by luboslenco** [comment]
Cool, thanks! Should be alright.

**Comment by luboslenco** [comment]
@donalffons noticed that ammo.js raised from 1597KB to 1865KB, is there anything we can do about it? I suppose this is pulled in from the additions.:/ I kept the older/smaller ammo.js for now, maybe we can figure something out..

**Comment by luboslenco** [comment]
Thinking of maybe having two ammo files, a light-weight one without soft bodies and the other one full-featured. Armory can then automatically pull in correct one based on soft body usage.

**Comment by donalffons** [comment]
Oh yes, I made some more changes to Ammo.JS that I did not create a pull request for, yet (mainly adding the addForce(...) function if I remember correctly). I will make a pull request for these changes in the Ammo.JS repository.

**Comment by donalffons** [comment]
...right, that's quite a size increase. Hmm, if you can set this up in a way, that makes it easy to keep track of both versions, I'm all for it.

**Comment by donalffons** [comment]
JFYI, this is the pull request for Ammo.JS including the new functions: https://github.com/kripken/ammo.js/pull/186

**Comment by guzzard** [comment]
@donalffons @luboslenco I got a bigger ammo.js as well when compiling on my box.. so I think it might have to do with compiler/optimizations perhaps? I meant to ask kripken how to compile a smaller size lib but haven't gotten around to it yet..

**Comment by donalffons** [comment]
@guzzard @luboslenco I just recompiled the latest official kripken/ammo.js version as a test. It has 1.902.318 bytes vs 1.635.200 bytes in the official build version. I will leave a note in my pull request on kripken/ammo.js, asking kripken to recompile the builds with his setup.

**Comment by donalffons** [comment]
@luboslenco @guzzard jfyi, Ammo.JS has just been updated with smaller build sizes. So, I guess there is no need for an extra version at the moment.

**Comment by luboslenco** [comment]
It's in! https://github.com/armory3d/haxebullet/commit/3618f8dabf0ac5ea9d09398beeb076886da830e3

**Pull request merged**
